version: 2
project_name: kvrocks-exporter
release:
  github:
    owner: RocksLabs
    name: kvrocks_exporter

builds:
  - id: kvrocks-exporter
    binary: kvrocks_exporter
    ldflags:
      - "-X main.BuildVersion={{ .Version }}"
      - "-X main.BuildDate={{.Date}}"
      - "-X main.BuildCommitSha={{.Commit}}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
kos:
  - repository: docker.io/kvrocks/kvrocks-exporter
    tags:
      - "{{.Version}}"
      - latest
    preserve_import_paths: false
    base_image: alpine:3.20
    bare: true 
    ldflags:
      - "-X main.BuildVersion={{ .Version }}"
      - "-X main.BuildDate={{.Date}}"
      - "-X main.BuildCommitSha={{.Commit}}"
    platforms:
      - linux/amd64
      - linux/arm64
