name: docker-build-push

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to  docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and publish image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/kvrocks-exporter" \
          --label "org.opencontainers.image.description=kvrocks-exporter image" \
          --label "org.opencontainers.image.licenses=Apache-2.0" \
          --push \
          -t docker.io/kvrocks/kvrocks-exporter:latest \
          -f Dockerfile \
          .
